// AUTO-GENERATED by scripts/gen-changelog.mjs — do not edit by hand.
// Refresh with: npm run changelog
// A changelog keeps only consumer-facing changes (feat/fix/breaking); internal churn is filtered out.
export type ChangelogEntry = {
  date: string;
  type: "feat" | "fix" | "breaking";
  scope: string | null;
  summary: string;
  hash: string;
  refs: string[];
};

export const CHANGELOG: { generatedFrom: string; kept: number; entries: ChangelogEntry[] } = {
  "generatedFrom": "main",
  "kept": 1,
  "entries": [
    {
      "date": "2026-10-03",
      "type": "feat",
      "scope": null,
      "summary": "dsiab, a brand-themeable design system on Radix Themes",
      "hash": "e80593e",
      "refs": []
    }
  ]
};
