/* =============================================================================
   src/index.ts — THE PUBLIC SURFACE
   -----------------------------------------------------------------------------
   Everything a consumer can `import { … } from "dsiab"` is in this file,
   and nothing else is. It has three sections, and they are governed differently:

     1. THEME — `Provider` and the types needed to write a wrapper against it.
        Hand-listed here; short enough to read, and each name is a decision.
     2. COMPONENTS — re-exported from `./components/ui`, which is GENERATED from
        `registry.json` by `scripts/gen-barrel.mjs`. Registering a component is
        what publishes it; nothing reaches a consumer without a registry entry.
        The specifier list below is GENERATED by that same command, between the
        `gen-barrel:begin` / `gen-barrel:end` markers — a hand-kept mirror of the
        barrel would drift the moment someone added a component and refreshed only
        one of the two files. Edit `registry.json`, then run `npm run barrel`.
     3. RADIX GAP-FILLERS — a CURATED subset of the names `@radix-ui/themes`
        exports that this system does not wrap. Radix publishes 103 names; this
        system wraps 57 of them and leaves 46 unwrapped. The 46 were ruled one at
        a time: 30 ship as Radix's OWN binding — 20 named in section 3 below, 10
        through a registered component whose module is a bare re-export — and 16
        do not ship at all. Adding a name to section 3 is a DECISION about what
        this system endorses, not a convenience.

   THE CENSUS, AND THE GUARD THAT KEEPS IT TRUE
   -----------------------------------------------------------------------------
   `src/foundations/radix-surface.node-check.ts` re-derives every number below
   from `@radix-ui/themes`'s own export surface on each test run, and reads them
   back out of this block. They are the record, not a description of one, and a
   stale one fails the suite:

     radix-names            103   every name `@radix-ui/themes` exports
     wrapped                 57   the binding a consumer gets is this system's own
     kept                    30   the binding is Radix's own, re-exported on purpose
       in-section-3          20   named one by one in section 3 below
       through-a-component   10   a registered module whose body is one re-export
     dropped                 16   not exported at all; the reasons close this file

   CORRECTED 2026-08-05 — this block previously read 67 wrapped / 36 unwrapped.
   Ten names (`AspectRatio`, `Grid`, `Section`, `Skeleton`, `VisuallyHidden` and
   their five `*Props`) were counted as wrapped while shipping Radix's own
   binding, and section 3 below positively called two of them "wrapped". The old
   figures added up — 67 + 36 = 103 — which is why nobody checked them against
   Radix; an internally consistent count is not a measured one. The guard is the
   difference, and it fails on a Radix release that adds a name too.

   WHY EVERY RE-EXPORT IS NAMED, AND `export *` APPEARS NOWHERE
   -----------------------------------------------------------------------------
   A name exported by two `export *` statements is silently DROPPED by the ES
   module spec — no error, at build time or at run time. A name exported by one
   `export *` and one explicit statement is silently SHADOWED by the explicit
   one. Both failures land exactly where they cost the most: 57 names carry a
   binding of this system's own AND a Radix binding of the same name, so a star
   re-export would decide those 57 collisions by accident, and a `Box` wrapper
   added tomorrow would lose to Radix's `Box` without a word. (The 30 kept names
   are not collisions — both stars resolve to the same binding, and a name whose
   two stars agree survives; only a genuine disagreement is dropped.) Written out
   name by name, the same collision is a compile error ("Module … has already
   exported a member named 'Box'") the moment it is introduced.
   ============================================================================= */

/* ---- 1. Theme -------------------------------------------------------------
   `Provider` is the root. It seeds the accent, the global size tier, the
   contrast model and the button order, and imports the token layer — mount it
   once, above everything else. `ContrastMode` / `UISize` / `ButtonOrder` are
   the union types those props take: a consumer writing a wrapper needs to name
   them, and re-deriving them by hand is how a private copy starts drifting. */
export { Provider, type ProviderProps, type ContrastMode } from "./theme/Provider";
export { Contrast } from "./theme/Contrast";
export { type UISize } from "./theme/SizeContext";
export { type ButtonOrder } from "./theme/ButtonOrderContext";

/* `version` is the one name here that is not part of the theme, and it is
   deliberately in section 1 rather than a section of its own: it is a fact about
   the package, hand-listed like the four above, and nothing generates it.

   It exists so a bug report can name the artifact it came from. Before it, the
   version string appeared in `dist/index.js` zero times, so two builds were
   indistinguishable from inside a consuming app and the only answer to "which
   version are you on?" depended on the reporter reading their own lockfile
   correctly. See `src/version.ts` for how the value gets in, and for why it
   reads `0.0.0-dev` outside a library build. */
export { version } from "./version";

/* ---- 2. Components --------------------------------------------------------
   Generated from `src/components/ui/index.ts`, which is itself generated from
   `registry.json`.

   ONE NAME IN THE LIST IS NOT A COMPONENT. `useOptionalFieldControl` reads the
   `Field.Root` above it and returns that field's `id` / `aria-describedby` /
   `aria-invalid`, or `null` when there is no Field.Root above it. Read what that
   means from OUT HERE, because it is not what it means inside this repo: the
   `Field` shell is internal by ruling and is NOT exported, so the only Field.Roots
   in a consumer's tree are the ones the inputs render for themselves. The hook
   therefore answers non-null only from inside one of those inputs — content passed
   into a `TextField`'s slot, say — and `null` everywhere else. It cannot be used to
   give a hand-built control the shell's label / description / validation chrome,
   because reaching that needs `Field.Root`, and `Field.Root` does not ship.

   THE SUPPORTED WAY TO GET AN INPUT WITH LABEL, HELPER TEXT AND VALIDATION is the
   wrapped inputs, which ride the shell already and hand it to you as props —
   `label`, `description`, `validation`, and `info` / `endSlot` where the label row
   takes them. Which components those are is deliberately not a roster here (a
   roster in prose is a copy that rots): every input's `Props` story carries its own
   prop table, and `validation?:` under src/components/ui finds them all at once.
   Composing the shell by hand is not a supported extension point — it is a second
   way to build an input that bypasses the rules the wrappers exist to enforce.

   `Field`'s registry entry publishes that one hook and lists the other fifteen
   names it withholds, this one included. GROUP-LEVEL VALIDATION IS A KNOWN GAP:
   `FieldGroup` is withheld too, and `CheckboxGroup` / `RadioGroup` take no `label`
   or `validation` of their own, so a group-level error message has no published
   route today. */
/* gen-barrel:begin — GENERATED; run `npm run barrel`. Nothing between the markers is hand-edited. */
export {
  type AccentColor,
  AlertDialog,
  type AnnouncePoliteness,
  AppShell,
  type AppShellProps,
  type AppShellVariant,
  AspectRatio,
  type AspectRatioProps,
  Avatar,
  AvatarGroup,
  type AvatarGroupProps,
  type AvatarProps,
  type AvatarStatus,
  Badge,
  type BadgeProps,
  type BadgeTone,
  Blockquote,
  type BlockquoteProps,
  BreadcrumbContext,
  type BreadcrumbContextValue,
  BreadcrumbItem,
  type BreadcrumbItemProps,
  Breadcrumbs,
  type BreadcrumbsProps,
  type BreadcrumbsVariant,
  type BreadcrumbsVariantMap,
  Button,
  ButtonGroup,
  type ButtonGroupProps,
  type ButtonPriority,
  type ButtonProps,
  type ButtonTone,
  Calendar,
  type CalendarProps,
  type CalendarRangeProps,
  type CalendarSingleProps,
  Callout,
  type CalloutActionPlacement,
  type CalloutProps,
  type CalloutTone,
  type CalloutUrgency,
  Card,
  type CardProps,
  type CardVariant,
  Carousel,
  type CarouselProps,
  type CarouselSpace,
  ChatComposer,
  type ChatComposerProps,
  type ChatComposerStatus,
  type ChatComposerStatusTone,
  ChatLayout,
  type ChatLayoutHandle,
  type ChatLayoutProps,
  ChatLayoutScrollButton,
  type ChatLayoutScrollButtonProps,
  type ChatListContextValue,
  ChatMessage,
  type ChatMessageContextValue,
  type ChatMessageGroup,
  ChatMessageList,
  type ChatMessageListProps,
  ChatMessageMetadata,
  type ChatMessageMetadataProps,
  type ChatMessageProps,
  type ChatMessageSender,
  type ChatMessageStatus,
  type ChatMessageVariant,
  ChatSystemMessage,
  type ChatSystemMessageProps,
  type ChatSystemMessageVariant,
  type ChatToolCallItem,
  type ChatToolCallStatus,
  ChatToolCalls,
  type ChatToolCallsProps,
  Checkbox,
  CheckboxCards,
  CheckboxGroup,
  type CheckboxProps,
  Citation,
  type CitationProps,
  type CitationSource,
  ClickableCard,
  type ClickableCardProps,
  Code,
  type CodeProps,
  Collapsible,
  CollapsibleGroup,
  type CollapsibleGroupItemProps,
  type CollapsibleGroupRootProps,
  type CollapsibleProps,
  type CollisionBehavior,
  CommandPalette,
  type CommandPaletteProps,
  ContextMenu,
  type ContextMenuItemProps,
  DataList,
  type DataListOverflow,
  type DataListRootProps,
  type DataListValueProps,
  DateInput,
  type DateInputProps,
  DateRangeInput,
  type DateRangeInputProps,
  type DateRangePreset,
  DateTimeInput,
  type DateTimeInputProps,
  Dialog,
  type DismissFn,
  DragHandle,
  type DragHandleOrientation,
  type DragHandleProps,
  DropdownMenu,
  type DropdownMenuItemProps,
  EmptyState,
  type EmptyStateProps,
  FileInput,
  type FileInputProps,
  FormLayout,
  type FormLayoutDirection,
  type FormLayoutProps,
  Grid,
  type GridProps,
  Heading,
  type HeadingProps,
  HoverCard,
  type ISODateTimeString,
  IconButton,
  type IconButtonPriority,
  type IconButtonProps,
  type IconButtonTone,
  Kbd,
  type KbdProps,
  Layout,
  LayoutContent,
  type LayoutContentProps,
  LayoutFooter,
  type LayoutFooterProps,
  LayoutHeader,
  type LayoutHeaderProps,
  type LayoutPadding,
  LayoutPanel,
  type LayoutPanelProps,
  type LayoutProps,
  type LayoutResizableOptions,
  Lightbox,
  type LightboxMedia,
  type LightboxMediaType,
  type LightboxProps,
  Link,
  type LinkComponent,
  type LinkProps,
  LinkProvider,
  List,
  type ListDensity,
  ListItem,
  type ListItemProps,
  type ListProps,
  type ListStyle,
  type MenuSize,
  MobileNav,
  type MobileNavConfig,
  type MobileNavProps,
  type MobileNavSide,
  MobileNavToggle,
  type MobileNavToggleProps,
  MoreMenu,
  type MoreMenuProps,
  MultiSelect,
  type MultiSelectProps,
  NumberInput,
  type NumberInputProps,
  Outline,
  type OutlineItem,
  type OutlineProps,
  type OverflowGap,
  type OverflowItem,
  OverflowList,
  type OverflowListProps,
  Overlay,
  type OverlayPosition,
  type OverlayProps,
  type OverlayScrim,
  type OverlayShowOn,
  Pagination,
  type PaginationProps,
  type PaginationSize,
  type PaginationVariant,
  type PaginationVariantMap,
  Popover,
  type PopoverContentProps,
  PowerSearch,
  type PowerSearchProps,
  Progress,
  type ProgressProps,
  RadioCards,
  RadioGroup,
  type ReorderChange,
  type ReorderGroup,
  type ReorderGroupProps,
  type ReorderHandleProps,
  type ReorderInstructionsProps,
  type ReorderItemProps,
  type ReorderPosition,
  ResizeHandle,
  type ResizeHandleProps,
  ScrollArea,
  type ScrollAreaProps,
  Section,
  type SectionProps,
  SegmentedControl,
  type SegmentedControlItemProps,
  Select,
  type SelectRootProps,
  Separator,
  type SeparatorProps,
  SideNav,
  SideNavCollapseButton,
  type SideNavCollapseButtonProps,
  SideNavHeading,
  type SideNavHeadingProps,
  SideNavItem,
  type SideNavItemProps,
  type SideNavProps,
  SideNavSection,
  type SideNavSectionProps,
  type SizeLane,
  Skeleton,
  type SkeletonProps,
  Slider,
  type SliderMark,
  type SliderProps,
  type SpaceStep,
  Spinner,
  type SpinnerProps,
  StatusDot,
  type StatusDotProps,
  type StatusDotVariant,
  Switch,
  type SwitchProps,
  Table,
  Tabs,
  type TabsNavLinkProps,
  type TabsSize,
  Text,
  TextArea,
  type TextAreaProps,
  TextField,
  type TextFieldProps,
  type TextProps,
  Thumbnail,
  type ThumbnailProps,
  TimeInput,
  type TimeInputProps,
  Timestamp,
  type TimestampFormat,
  type TimestampProps,
  type ToastAction,
  type ToastOptions,
  type ToastPosition,
  ToastProvider,
  type ToastProviderProps,
  type ToastTone,
  ToastViewport,
  type ToastViewportProps,
  ToggleButton,
  ToggleButtonGroup,
  type ToggleButtonGroupItemProps,
  type ToggleButtonGroupRootProps,
  type ToggleButtonProps,
  Token,
  type TokenProps,
  type TokenRemoveEvent,
  Tokenizer,
  type TokenizerChange,
  type TokenizerProps,
  Toolbar,
  type ToolbarProps,
  ToolbarRoot,
  ToolbarSeparator,
  type ToolbarSeparatorProps,
  Tooltip,
  type TooltipProps,
  TopNav,
  TopNavHeading,
  type TopNavHeadingProps,
  TopNavItem,
  type TopNavItemProps,
  TopNavMegaMenu,
  TopNavMegaMenuFeaturedCard,
  type TopNavMegaMenuFeaturedCardProps,
  TopNavMegaMenuItem,
  type TopNavMegaMenuItemProps,
  type TopNavMegaMenuProps,
  TopNavMenu,
  type TopNavMenuProps,
  type TopNavProps,
  TreeList,
  type TreeListDensity,
  type TreeListItemData,
  type TreeListProps,
  Typeahead,
  type TypeaheadOption,
  type TypeaheadProps,
  type TypeaheadSource,
  type UseLightboxOptions,
  type UseLightboxReturn,
  type UseReorderOptions,
  type UseReorderReturn,
  VisuallyHidden,
  type VisuallyHiddenProps,
  combineDateTime,
  createStaticSource,
  interactiveLayer,
  isRangeEqual,
  splitDateTime,
  useAnnounce,
  useClampedMenuSize,
  useFormLayoutDirection,
  useLightbox,
  useLinkComponent,
  useMediaQuery,
  useOptionalChatList,
  useOptionalChatMessage,
  useOptionalFieldControl,
  useReorder,
  useSizeLane,
  useToast,
  useUISize,
} from "./components/ui";
/* gen-barrel:end */

/* ---- 3. Radix gap-fillers -------------------------------------------------
   Layout, inline text, and composition primitives this system does not wrap.
   What they have in common is that no design decision passes through them:
   they carry no tone, no size step, no focus ring and no token — so there is
   no fidelity for a consumer to lose by reaching for one, and re-implementing
   them locally would be the drift. Everything that DOES carry a decision is
   wrapped in section 2 and must be taken from there. */
export {
  // Layout. `Grid`, `Section` and `AspectRatio` ship through section 2 — as Radix's own
  // binding, not as wrappers (see the KEPT block below); these four are the rest.
  Box,
  type BoxProps,
  Container,
  type ContainerProps,
  Flex,
  type FlexProps,
  Inset,
  type InsetProps,
  // Inline text. `Text`, `Heading`, `Code` and `Blockquote` are wrapped; these three are the rest.
  Em,
  type EmProps,
  Quote,
  type QuoteProps,
  Strong,
  type StrongProps,
  // Composition. `Slot`/`Slottable` merge props onto a child and render no DOM of
  // their own — they are how a consumer gives their OWN wrapper an `asChild` prop.
  // `Reset` strips a native element (a `ul`, a `button`) back to a neutral baseline.
  Reset,
  type ResetProps,
  Slot,
  Slottable,
  // Accessibility. Names an icon for a screen reader; no visual output.
  AccessibleIcon,
  type AccessibleIconProps,
} from "@radix-ui/themes";

/* KEPT THROUGH SECTION 2 — the other 10 of the 30 that keep. Each is a registered
   component whose module is a single line, `export { … } from "@radix-ui/themes"`:
   it earns a registry entry, a story and a docs page, but the binding a consumer
   imports is Radix's own, so it is a KEEP and not a wrapper. Section 2's list is
   generated and cannot say which of its names those are, and until 2026-08-05 this
   file said the opposite of two of them — so the record lives here:

     AspectRatio,             Layout only. No paint, no role, no size lane.
       AspectRatioProps
     Grid, GridProps          Pure layout; `gap` rides the `--space` scale.
     Section, SectionProps    Vertical padding passed through untouched.
     Skeleton,                Sizes itself to the children it wraps; reuses Radix's
       SkeletonProps          own gray skin rather than restating it.
     VisuallyHidden,          The announce-only pattern — clipped to 1px, kept in the
       VisuallyHiddenProps    accessibility tree. No visual output.

   Wrapping one of these later moves it out of this block on its own: the binding
   stops being Radix's, and the guard fails until the block and the census agree. */

/* DELIBERATELY NOT EXPORTED — the 16 of the 46 that do not ship at all. Re-exporting
   one is a ruling, not an oversight, and each of these has a live reason to stay out:

     Theme, ThemeProps        `Provider` IS this, with the token layer attached and
                              the better-known name. Reaching for `Theme` yields Radix
                              defaults with no `--ds-*` layer, no warning, and the whole
                              subtree quietly off-system.
     ThemePanel,              A development debug panel.
       ThemePanelProps
     ThemeContext,            The vendor's theming plumbing, which `Provider` owns. Reading
       useThemeContext        or writing it is how a second source of truth for the theme
                              starts.
     Radio, RadioProps        `RadioGroup` and `RadioCards` are wrapped: they resolve the
                              global size tier and wire themselves into the Field shell's
                              aria. Bare `Radio` is an `<input type="radio">` that does
                              neither — a second fidelity inside one family.
     TabNav                   Wrapped, as `Tabs.Nav` / `Tabs.Nav.Link`: same size lane as
                              the panel list, and links routed through `useLinkComponent`.
                              The raw namespace bypasses both.
     Portal, PortalProps      Radix Themes' `Portal` is `radix-ui`'s `Portal.Root`
                              verbatim — it does NOT re-establish the theme root, so
                              every token inside it goes unresolved, and with `Theme`
                              unexported there is no supported way to put it back. The
                              floating surfaces that need a portal (Dialog, Popover,
                              Tooltip, HoverCard, DropdownMenu, ContextMenu, Overlay,
                              CommandPalette, AlertDialog) each own theirs.
     ChevronDownIcon,         Radix's four internal icons, undocumented on its own site.
       ThickCheckIcon,        This system draws with @phosphor-icons/react; these four
       ThickChevronRightIcon, are a second icon family with a different weight and grid.
       ThickDividerHorizontalIcon
     IconProps                The props type of those four icons, and of nothing else. */
